/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package kasircoba;

import java.sql.Connection;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import java.sql.SQLException;
import java.sql.Statement;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author ASUS
 */
public class gudang extends javax.swing.JFrame {
    Connection con = config_db.config_db();
    private ResultSet res;
    private Statement stm;
    private PreparedStatement ps;
    String sql, barang;
    int karyawan, i, cek_id, cek_id2, stok, stok2, total_stok, act;
    int indeks = 2;
    /**
     */
    public gudang(int kr) {
        initComponents();
        karyawan = kr;
        try{
            stm = con.createStatement();
            sql = "select * from karyawan where id_karyawan = '" + karyawan +"';";
            res = stm.executeQuery(sql);
            res.next();
            nama.setText("(" + res.getString("nama_karyawan") + ")");
            showBarang();
            showSupplier();
            showAct();
        } catch(SQLException e){
            JOptionPane.showMessageDialog(null, "Terdapat Permasalahan di "+ e);
        }
    }


    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane1 = new javax.swing.JScrollPane();
        list_supplier = new javax.swing.JTable();
        jLabel1 = new javax.swing.JLabel();
        nama = new javax.swing.JLabel();
        changeUser = new javax.swing.JButton();
        tambahSupplier = new javax.swing.JButton();
        jLabel2 = new javax.swing.JLabel();
        jScrollPane2 = new javax.swing.JScrollPane();
        log_activity = new javax.swing.JTable();
        jLabel3 = new javax.swing.JLabel();
        jScrollPane3 = new javax.swing.JScrollPane();
        list_barang = new javax.swing.JTable();
        del = new javax.swing.JButton();
        update = new javax.swing.JButton();
        findNama = new javax.swing.JTextField();
        jLabel4 = new javax.swing.JLabel();
        jSeparator1 = new javax.swing.JSeparator();
        jLabel5 = new javax.swing.JLabel();
        idBrg = new javax.swing.JTextField();
        jLabel6 = new javax.swing.JLabel();
        namaBrg = new javax.swing.JTextField();
        jLabel7 = new javax.swing.JLabel();
        jenisBrg = new javax.swing.JTextField();
        jLabel8 = new javax.swing.JLabel();
        stokBrg = new javax.swing.JTextField();
        jLabel9 = new javax.swing.JLabel();
        hbBrg = new javax.swing.JTextField();
        jLabel10 = new javax.swing.JLabel();
        hjBrg = new javax.swing.JTextField();
        exit = new javax.swing.JButton();
        jSeparator2 = new javax.swing.JSeparator();
        refresh = new javax.swing.JButton();
        idSup = new javax.swing.JTextField();
        jLabel12 = new javax.swing.JLabel();
        add = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        list_supplier.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        jScrollPane1.setViewportView(list_supplier);

        jLabel1.setFont(new java.awt.Font("Verdana", 0, 18)); // NOI18N
        jLabel1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel1.setText("GUDANG");

        nama.setFont(new java.awt.Font("Verdana", 0, 14)); // NOI18N
        nama.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);

        changeUser.setText("GANTI USER");
        changeUser.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                changeUserActionPerformed(evt);
            }
        });

        tambahSupplier.setText("TAMBAH SUPPLIER");
        tambahSupplier.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                tambahSupplierActionPerformed(evt);
            }
        });

        jLabel2.setText("LIST SUPPLIER");

        log_activity.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        jScrollPane2.setViewportView(log_activity);

        jLabel3.setText("LOG AKTIVITAS");

        list_barang.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        list_barang.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                list_barangMouseClicked(evt);
            }
        });
        jScrollPane3.setViewportView(list_barang);

        del.setText("DELETE");
        del.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                delActionPerformed(evt);
            }
        });

        update.setText("UPDATE");
        update.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                updateActionPerformed(evt);
            }
        });

        findNama.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                findNamaKeyReleased(evt);
            }
        });

        jLabel4.setText("CARI BARANG :");

        jSeparator1.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        jSeparator1.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        jSeparator1.setDebugGraphicsOptions(javax.swing.DebugGraphics.NONE_OPTION);

        jLabel5.setText("ID Barang :");

        jLabel6.setText("Nama Barang :");

        jLabel7.setText("Jenis Barang :");

        jLabel8.setText("Stok Barang :");

        jLabel9.setText("Harga Beli :");

        jLabel10.setText("Harga Jual :");

        exit.setText("EXIT");
        exit.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                exitActionPerformed(evt);
            }
        });

        jSeparator2.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));

        refresh.setText("REFRESH");
        refresh.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                refreshActionPerformed(evt);
            }
        });

        jLabel12.setText("ID Supplier :");

        add.setText("ADD");
        add.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                addActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jSeparator2, javax.swing.GroupLayout.PREFERRED_SIZE, 872, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 102, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(nama, javax.swing.GroupLayout.PREFERRED_SIZE, 253, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 93, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(refresh, javax.swing.GroupLayout.PREFERRED_SIZE, 99, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 388, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 131, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jScrollPane1, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 388, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(tambahSupplier, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 173, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addGap(6, 6, 6)
                                .addComponent(changeUser, javax.swing.GroupLayout.PREFERRED_SIZE, 135, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(exit))
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jSeparator1, javax.swing.GroupLayout.PREFERRED_SIZE, 2, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(18, 18, 18)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                        .addGroup(layout.createSequentialGroup()
                                            .addComponent(jLabel4, javax.swing.GroupLayout.PREFERRED_SIZE, 93, javax.swing.GroupLayout.PREFERRED_SIZE)
                                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                            .addComponent(findNama, javax.swing.GroupLayout.PREFERRED_SIZE, 250, javax.swing.GroupLayout.PREFERRED_SIZE))
                                        .addComponent(jScrollPane3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                                    .addGroup(layout.createSequentialGroup()
                                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                            .addGroup(layout.createSequentialGroup()
                                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                                    .addComponent(jLabel5, javax.swing.GroupLayout.Alignment.TRAILING)
                                                    .addComponent(jLabel6, javax.swing.GroupLayout.Alignment.TRAILING)
                                                    .addComponent(jLabel7, javax.swing.GroupLayout.Alignment.TRAILING)
                                                    .addComponent(jLabel8, javax.swing.GroupLayout.Alignment.TRAILING)
                                                    .addComponent(jLabel9, javax.swing.GroupLayout.Alignment.TRAILING)
                                                    .addComponent(jLabel10, javax.swing.GroupLayout.Alignment.TRAILING)
                                                    .addComponent(jLabel12, javax.swing.GroupLayout.Alignment.TRAILING))
                                                .addGap(18, 18, 18)
                                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                                    .addComponent(idBrg)
                                                    .addComponent(namaBrg)
                                                    .addComponent(jenisBrg)
                                                    .addComponent(stokBrg)
                                                    .addComponent(hbBrg)
                                                    .addComponent(hjBrg, javax.swing.GroupLayout.PREFERRED_SIZE, 253, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                    .addComponent(idSup, javax.swing.GroupLayout.PREFERRED_SIZE, 253, javax.swing.GroupLayout.PREFERRED_SIZE)))
                                            .addGroup(layout.createSequentialGroup()
                                                .addComponent(add, javax.swing.GroupLayout.PREFERRED_SIZE, 75, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                                .addComponent(update, javax.swing.GroupLayout.PREFERRED_SIZE, 86, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                                .addComponent(del, javax.swing.GroupLayout.PREFERRED_SIZE, 84, javax.swing.GroupLayout.PREFERRED_SIZE)))
                                        .addGap(87, 87, 87)))))))
                .addContainerGap(14, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jLabel1, javax.swing.GroupLayout.DEFAULT_SIZE, 36, Short.MAX_VALUE)
                    .addComponent(nama, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(changeUser)
                        .addComponent(exit)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jSeparator2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                .addComponent(jLabel4, javax.swing.GroupLayout.PREFERRED_SIZE, 22, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(findNama, javax.swing.GroupLayout.PREFERRED_SIZE, 38, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 22, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(refresh)))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jScrollPane3, javax.swing.GroupLayout.PREFERRED_SIZE, 230, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(idSup, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jLabel12))
                                .addGap(18, 18, 18)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(jLabel5)
                                    .addComponent(idBrg, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGap(18, 18, 18)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(jLabel6)
                                    .addComponent(namaBrg, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGap(18, 18, 18)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(jLabel7)
                                    .addComponent(jenisBrg, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGap(18, 18, 18)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(jLabel8)
                                    .addComponent(stokBrg, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGap(18, 18, 18)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(jLabel9)
                                    .addComponent(hbBrg, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGap(18, 18, 18)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(jLabel10)
                                    .addComponent(hjBrg, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 18, Short.MAX_VALUE)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(update)
                                    .addComponent(del)
                                    .addComponent(add)))
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 187, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(tambahSupplier)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 22, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 187, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(56, 56, 56))))
                    .addComponent(jSeparator1))
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void changeUserActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_changeUserActionPerformed
        // TODO add your handling code here:
        this.dispose();
        new loginKasir(indeks).setVisible(true);
    }//GEN-LAST:event_changeUserActionPerformed

    private void showBarang(){
        DefaultTableModel m = new DefaultTableModel(){
            @Override
            public boolean isCellEditable(int row, int column){
                return false;
            }
        };
        m.addColumn("Id Barang");
        m.addColumn("Id Supplier");
        m.addColumn("Nama Barang");
        m.addColumn("Jenis Barang");
        m.addColumn("Stok");
        m.addColumn("Harga Beli");
        m.addColumn("Harga Jual");
        try{
            stm = con.createStatement();
            sql = "select * from barang;";
            res = stm.executeQuery(sql);
            while(res.next()){
                m.addRow(new Object[]{res.getString("id_barang"),
                    res.getString("id_supplier"),
                    res.getString("nama_barang"),
                    res.getString("jenis_barang"),
                    res.getString("stok_barang"),
                    res.getString("harga_beli"),
                    res.getString("harga_jual")});
            }
            list_barang.setModel(m);
        }catch(NumberFormatException | SQLException e){
            JOptionPane.showMessageDialog(null, "Terdapat Permasalahan di "+ e);
        }
    }
    
    private void showSupplier(){
        DefaultTableModel m2 = new DefaultTableModel(){
            @Override
            public boolean isCellEditable(int row, int column){
                return false;
            }
        };
        m2.addColumn("Id Supplier");
        m2.addColumn("Nama Supplier");
        m2.addColumn("Alamat");
        m2.addColumn("No Telp");
        try{
            stm = con.createStatement();
            sql = "select * from supplier;";
            res = stm.executeQuery(sql);
            while(res.next()){
                m2.addRow(new Object[]{res.getString("id_supplier"),
                    res.getString("nama_supplier"),
                    res.getString("alamat_supplier"),
                    res.getString("notelp_supplier")});
            }
            list_supplier.setModel(m2);
        }catch(NumberFormatException | SQLException e){
            JOptionPane.showMessageDialog(null, "Terdapat Permasalahan di "+ e);
        }
    }
    
    private void showAct(){
        DefaultTableModel m3 = new DefaultTableModel(){
            @Override
            public boolean isCellEditable(int row, int column){
                return false;
            }
        };
        m3.addColumn("Id");
        m3.addColumn("Nama Kegiatan");
        m3.addColumn("Keterangan");
        m3.addColumn("Tanggal");
        try{
            stm = con.createStatement();
            sql = "select log.id_activity, j.nama_activity, log.keterangan, log.tanggal_activity"
                    + " from log_activity log inner join jenis_activity j on log.id_jenisactivity = j.id_jenisactivity where id_karyawan = '" + karyawan + "';";
            res = stm.executeQuery(sql);
            while(res.next()){
                m3.addRow(new Object[]{res.getString("log.id_activity"),
                    res.getString("j.nama_activity"),
                    res.getString("log.keterangan"),
                    res.getString("log.tanggal_activity")});
            }
            log_activity.setModel(m3);
        }catch(NumberFormatException | SQLException e){
            JOptionPane.showMessageDialog(null, "Terdapat Permasalahan di "+ e);
        }
    }
    private void insertAct(){
        try{
            sql = "insert into log_activity value (null, '" + karyawan + "','" + act + "','" + idBrg.getText() + "', now());";
            ps = con.prepareStatement(sql);
            ps.execute();
        }catch (SQLException e) {
            JOptionPane.showMessageDialog(null, "Terdapat Permasalahan di "+ e);
        }
    }
    
    private void clearForm(){
        idSup.setText(null);
        idBrg.setText(null);
        namaBrg.setText(null);
        jenisBrg.setText(null);
        stokBrg.setText(null);
        hbBrg.setText(null);
        hjBrg.setText(null);
    }
    
    private void exitActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_exitActionPerformed
        // TODO add your handling code here:
        System.exit(0);
    }//GEN-LAST:event_exitActionPerformed

    private void findNamaKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_findNamaKeyReleased
        // TODO add your handling code here:
        String cari;
        cari = findNama.getText();
        DefaultTableModel m = new DefaultTableModel(){
            @Override
            public boolean isCellEditable(int row, int column){
                return false;
            }
        };
        m.addColumn("Id Barang");
        m.addColumn("Id Supplier");
        m.addColumn("Nama Barang");
        m.addColumn("Jenis Barang");
        m.addColumn("Stok");
        m.addColumn("Harga Beli");
        m.addColumn("Harga Jual");
        try{
            m.setRowCount(0);
            stm = con.createStatement();
            sql = "select * from barang where nama_barang like '%" + cari + "%';";
            res = stm.executeQuery(sql);
            while(res.next()){
                m.addRow(new Object[]{res.getString("id_barang"),
                    res.getString("id_supplier"), res.getString("nama_barang"), res.getString("jenis_barang"),
                    res.getString("stok_barang"), res.getString("harga_beli"), res.getString("harga_jual")});
            }
            list_barang.setModel(m);
        }catch(SQLException e){
            JOptionPane.showMessageDialog(null, "Terdapat permasalahan di " + e);
        }
    }//GEN-LAST:event_findNamaKeyReleased

    private void refreshActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_refreshActionPerformed
        // TODO add your handling code here:
            showBarang();
            showSupplier();
            showAct();
    }//GEN-LAST:event_refreshActionPerformed

    private void tambahSupplierActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_tambahSupplierActionPerformed
        // TODO add your handling code here:
        new form_supplier(karyawan).setVisible(true);
    }//GEN-LAST:event_tambahSupplierActionPerformed

    private void list_barangMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_list_barangMouseClicked
        // TODO add your handling code here:
        if(evt.getClickCount()==2){
            int row = list_barang.getSelectedRow();
            idSup.setText(list_barang.getValueAt(row, 1).toString());
            idBrg.setText(list_barang.getValueAt(row, 0).toString());
            namaBrg.setText(list_barang.getValueAt(row, 2).toString());
            jenisBrg.setText(list_barang.getValueAt(row, 3).toString());
            stokBrg.setText(list_barang.getValueAt(row, 4).toString());
            hbBrg.setText(list_barang.getValueAt(row, 5).toString());
            hjBrg.setText(list_barang.getValueAt(row, 6).toString());
            cek_id = Integer.parseInt(idBrg.getText());
            stok = Integer.parseInt(stokBrg.getText());
        }
    }//GEN-LAST:event_list_barangMouseClicked

    private void addActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_addActionPerformed
        // TODO add your handling code here:
        try{
            cek_id2 = Integer.parseInt(idBrg.getText());
            stok2 = Integer.parseInt(stokBrg.getText());
            total_stok = stok + stok2;
            act = 2;
            if(cek_id2 == cek_id){
                sql = "update barang set stok_barang = '" + total_stok + "' where id_barang = '" + cek_id2 + "';";
                ps = con.prepareStatement(sql);
                ps.execute();
                JOptionPane.showMessageDialog(null, namaBrg.getText() + " berhasil ditambahkan sebanyak " + stok2 + " pcs menjadi " + total_stok + " pcs!");
            }
            else{
                sql = "insert into barang value ('" + cek_id2 + "','" + Integer.parseInt(idSup.getText()) + "','"
                    + namaBrg.getText() + "','" + jenisBrg.getText() + "','" + stok2 + "','" + Integer.parseInt(hjBrg.getText()) + "','"
                    + Integer.parseInt(hbBrg.getText()) + "');";
                ps = con.prepareStatement(sql);
                ps.execute();
                JOptionPane.showMessageDialog(null, namaBrg.getText() + " berhasil ditambahkan sebanyak " + stok2 + " pcs!");
            }
            insertAct();
            clearForm();
        }catch (NumberFormatException | SQLException e){
            JOptionPane.showMessageDialog(null, "Terdapat permasalahan di " + e);
        }
    }//GEN-LAST:event_addActionPerformed

    private void updateActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_updateActionPerformed
        // TODO add your handling code here:
        try{
            act = 3;
            sql = "update barang set id_barang = '" + Integer.parseInt(idBrg.getText()) + "', id_supplier = '"
                    + Integer.parseInt(idSup.getText()) + "', nama_barang = '"
                    + namaBrg.getText() + "', jenis_barang = '" + jenisBrg.getText() + "', stok_barang = '"
                    + Integer.parseInt(stokBrg.getText()) + "', harga_jual = '" + Integer.parseInt(hjBrg.getText()) + "', harga_beli = '"
                    + Integer.parseInt(hbBrg.getText()) + "' where id_barang = '" + cek_id + "';";
            ps = con.prepareStatement(sql);
            ps.execute();
            JOptionPane.showMessageDialog(null,"Update Data Barang Sukses!");
            insertAct();
            clearForm();
        }catch(NumberFormatException | SQLException e){
            JOptionPane.showMessageDialog(null,"Terdapat Permasalahan di "+ e);
        }
    }//GEN-LAST:event_updateActionPerformed

    private void delActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_delActionPerformed
        // TODO add your handling code here:
        try{
            act = 4;
            cek_id2 = Integer.parseInt(idBrg.getText());
            stok2 = Integer.parseInt(stokBrg.getText());
            total_stok = stok - stok2;
            if(total_stok < 0){
                JOptionPane.showMessageDialog(null, "Stok yang dihapus kurang dari jumlah minimal!");
            }
            else{
                sql = "update barang set stok_barang = '" + total_stok + "' where id_barang = '" + cek_id2 + "';";
                ps = con.prepareStatement(sql);
                ps.execute();
                JOptionPane.showMessageDialog(null, namaBrg.getText() + " berhasil dihapus sebanyak " + stok2 + " pcs menjadi " + total_stok + " pcs!");
                insertAct();
                clearForm();
            }
        } catch(NumberFormatException | SQLException e){
            JOptionPane.showMessageDialog(null,"Terdapat Permasalahan di "+ e);
        }
    }//GEN-LAST:event_delActionPerformed

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton add;
    private javax.swing.JButton changeUser;
    private javax.swing.JButton del;
    private javax.swing.JButton exit;
    private javax.swing.JTextField findNama;
    private javax.swing.JTextField hbBrg;
    private javax.swing.JTextField hjBrg;
    private javax.swing.JTextField idBrg;
    private javax.swing.JTextField idSup;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JScrollPane jScrollPane3;
    private javax.swing.JSeparator jSeparator1;
    private javax.swing.JSeparator jSeparator2;
    private javax.swing.JTextField jenisBrg;
    private javax.swing.JTable list_barang;
    private javax.swing.JTable list_supplier;
    private javax.swing.JTable log_activity;
    private javax.swing.JLabel nama;
    private javax.swing.JTextField namaBrg;
    private javax.swing.JButton refresh;
    private javax.swing.JTextField stokBrg;
    private javax.swing.JButton tambahSupplier;
    private javax.swing.JButton update;
    // End of variables declaration//GEN-END:variables
}
